<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

<ItemGroup>
    <!-- BepInEx Core & Harmony -->
    <Reference Include="BepInEx">
      <HintPath>D:\SP_Tushonka\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>D:\SP_Tushonka\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>

    <!-- Newtonsoft JSON -->
    <Reference Include="Newtonsoft.Json">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>

    <!-- SPT Assemblies -->
    <Reference Include="spt-common">
      <HintPath>D:\SP_Tushonka\BepInEx\plugins\spt\spt-common.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>D:\SP_Tushonka\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>

    <!-- Tarkov & Unity Assemblies -->
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>D:\SP_Tushonka\EscapeFromTarkov_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Automatically copy output DLL to the BepInEx plugins directory on build -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFolder="D:\SP_Tushonka\BepInEx\plugins\Melx-LootValue\" />
  </Target>
</Project>